### ISSUE TITLE
Reviewing a dask recipe

### ISSUE THREAD

**Issue by rossant** [ipython-books/recipes-for-review#3]
Hi @mrocklin @jcrist

Would you be willing to do a short technical review of this dask recipe before Nov 24th for the upcoming IPython Cookbook, 2nd edition? It's just a matter of going through the recipe and let me know of any comments, errors, or things that I forgot to talk about.

If not, could you please let me know of anyone else who might be interested?

Thanks!

* [Performing out-of-core computations on large arrays with Dask](https://github.com/ipython-books/recipes-for-review/blob/master/chapter05/11_dask.md)

**Comment by mrocklin** [comment]
This looks great to me.  I like both the general framing of the project as well as the specific examples.  

If I were to change one thing it would be to increase the size of the dask.array to something that NumPy genuinely couldn't handle in RAM.  This moves the value add of Dask from "is more efficient" to "enables me to solve problems I didn't previously consider possible".  Perhaps a small note/example like the following:

> So now that Dask.array helps us manage larger datasets in less memory we feel free to manipulate arrays that would never fit in our computer.  Lets compute the average of a large terabyte erray ... 

It might also be handy to see a more pragmatic example, but this is obviously significantly more work.

**Comment by rossant** [comment]
Thanks @mrocklin ! I did your suggestion.
