### ISSUE TITLE
review of 2.1. Using the latest features of Python 3

### ISSUE THREAD

**Issue by glyg** [ipython-books/recipes-for-review#6]
Nice work!

### On format string
It could be nice to show that any python statement can go in a format string, simply by replacing:
```python
a, b, c = 1, 2, 3
f"The sum of {a} and {b} is {c}"
```
by:
```python
a, b = 1, 2
f"The sum of {a} and {b} is {a + b}"
```
It isn't much more complicated and conveys more info.

### use of `l`as a variable name

Minor case `l` is used for list all along the document, that's against PEP8, and I thought for a second you where assigning a list to the numeral 1 (only half kidding there).

### Greek characters
More on an opinion note, it is nice that one can use any unicode character, and jupyter makes it easy to type them, but I think putting greek letters in the code make it hard to maintain (e.g by exporting the code from the notebook to a script).

**Comment by rossant** [comment]
Great suggestions, thanks @glyg !
